services:
  web:
    build: .
    container_name: thrivecart_test_web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: thrivecart_test_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./conf/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  db_data:
